package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/dolthub/dolt/go/libraries/doltcore/servercfg"
	"github.com/dolthub/dolt/go/libraries/utils/filesys"
	"gopkg.in/yaml.v3"

	"github.com/steveyegge/beads/internal/config"
	"github.com/steveyegge/beads/internal/configfile"
	"github.com/steveyegge/beads/internal/storage"
	"github.com/steveyegge/beads/internal/storage/db/proxy"
	"github.com/steveyegge/beads/internal/storage/dolt"
	proxieddolt "github.com/steveyegge/beads/internal/storage/doltserver"
)

// Filesystem layout for --proxied-server (per workspace, all under one dir):
//
//	<root>/                       proxy lockfile, pidfile, child dolt repo
//	<root>/server_config.yaml     dolt sql-server YAML (host/port/log_level)
//	<root>/server.log             daemon stdout/stderr
//
// <root> is resolved by resolveProxiedServerRootPath: BEADS_PROXIED_SERVER_ROOT_PATH
// > metadata.json's dolt_proxied_server_root_path (set by `bd init
// --server-root-path <path>`) > the default <beadsDir>/proxieddb. The whole
// directory is owned by the per-workspace proxied dolt sql-server feature
// and (when at the default location) is gitignored.
//
// server_config.yaml's DEFAULT location cascades off <root>, so
// --server-root-path alone moves it. It is auto-generated by
// ensureProxiedServerConfig — UNLESS the caller has configured a custom path
// via BEADS_PROXIED_SERVER_CONFIG or metadata.json's dolt_proxied_server_config
// (set by `bd init --server-config <path>`). In that case bd validates the
// user-supplied file but never auto-creates one; the user owns its lifecycle.
//
// server.log's DEFAULT location also cascades off <root>; the proxy parent's
// O_CREATE|O_APPEND open creates it on first daemon spawn. The path can be
// independently redirected via BEADS_PROXIED_SERVER_LOG or metadata.json's
// dolt_proxied_server_log (set by `bd init --server-log-path <path>`). bd
// validates the parent directory exists and that any pre-existing target is
// a regular file, but never auto-creates user-supplied directories.
const (
	proxiedServerRootName   = "proxieddb"
	proxiedServerConfigName = "server_config.yaml"
	proxiedServerLogName    = "server.log"
)

func proxiedServerRoot(beadsDir string) string {
	return filepath.Join(beadsDir, proxiedServerRootName)
}

func proxiedServerConfigPath(beadsDir string) string {
	return filepath.Join(proxiedServerRoot(beadsDir), proxiedServerConfigName)
}

func proxiedServerLogPath(beadsDir string) string {
	return filepath.Join(proxiedServerRoot(beadsDir), proxiedServerLogName)
}

// resolveProxiedServerRootPath returns the proxied-server root directory the
// backend should use, plus a flag indicating whether the path is user-supplied
// (custom) or bd's default <beadsDir>/proxieddb.
//
// Resolution chain:
//  1. BEADS_PROXIED_SERVER_ROOT_PATH env var (highest; absolute paths welcome).
//  2. metadata.json's dolt_proxied_server_root_path field (relative to beadsDir).
//  3. The default proxiedServerRoot(beadsDir) → <beadsDir>/proxieddb.
//
// Steps 1+2 collapse into cfg.GetDoltProxiedServerRootPath. cfg may be nil
// when init runs before metadata.json has been written — we substitute an
// empty Config so the env-var check still happens.
//
// isCustom == true means "the user owns this directory": callers should
// validate it (validateProxiedServerRootPath) before using and must not
// silently mkdir arbitrary user paths. The default proxied-server config and
// log paths cascade off the resolved root, so changing the root also moves
// server_config.yaml and server.log unless they're independently overridden.
func resolveProxiedServerRootPath(beadsDir string, cfg *configfile.Config) (path string, isCustom bool) {
	if cfg == nil {
		cfg = &configfile.Config{}
	}
	if custom := cfg.GetDoltProxiedServerRootPath(beadsDir); custom != "" {
		return custom, true
	}
	return proxiedServerRoot(beadsDir), false
}

// resolveProxiedServerConfigPath returns the dolt sql-server YAML path the
// proxied-server backend should use, plus a flag indicating whether the path
// is user-supplied (custom) or bd's default.
//
// Resolution chain:
//  1. BEADS_PROXIED_SERVER_CONFIG env var (highest; absolute paths welcome).
//  2. metadata.json's dolt_proxied_server_config field (relative to beadsDir).
//  3. The default <resolvedRoot>/server_config.yaml, where resolvedRoot is
//     resolveProxiedServerRootPath(beadsDir, cfg). When no root override is
//     set this is <beadsDir>/proxieddb/server_config.yaml — preserving the
//     pre-cascade default. With --server-root-path=/X alone, the YAML moves
//     to /X/server_config.yaml without requiring --server-config too.
//
// Steps 1+2 collapse into cfg.GetDoltProxiedServerConfig (configfile owns
// the env-var name in one place); cfg may be nil here, e.g. when init runs
// before metadata.json has been written — we substitute an empty Config so
// the env-var check still happens.
//
// isCustom == true means "the user owns this file": callers must not
// auto-create it, and bd validates it exists rather than writing one. A
// cascaded default under a custom root is NOT marked custom — bd still
// owns the YAML's lifecycle there (auto-mkdir + auto-render with a free
// port), it just lives under a user-chosen root.
func resolveProxiedServerConfigPath(beadsDir string, cfg *configfile.Config) (path string, isCustom bool) {
	if cfg == nil {
		cfg = &configfile.Config{}
	}
	if custom := cfg.GetDoltProxiedServerConfig(beadsDir); custom != "" {
		return custom, true
	}
	root, _ := resolveProxiedServerRootPath(beadsDir, cfg)
	return filepath.Join(root, proxiedServerConfigName), false
}

// resolveProxiedServerLogPath returns the path the proxied dolt sql-server
// should write stdout/stderr to, plus a flag indicating whether the path is
// user-supplied (custom) or bd's default.
//
// Resolution chain mirrors resolveProxiedServerConfigPath:
//  1. BEADS_PROXIED_SERVER_LOG env var (highest; absolute paths welcome).
//  2. metadata.json's dolt_proxied_server_log field (relative to beadsDir).
//  3. The default <resolvedRoot>/server.log — cascaded off
//     resolveProxiedServerRootPath so --server-root-path alone relocates
//     the log alongside the config.
//
// isCustom == true means callers should validate the user-supplied path
// (parent dir exists, file-if-exists is regular) rather than trusting it
// blindly — bd never auto-creates parent directories the user gave us. A
// cascaded default under a custom root is NOT marked custom; root validation
// already covered the parent at init time.
func resolveProxiedServerLogPath(beadsDir string, cfg *configfile.Config) (path string, isCustom bool) {
	if cfg == nil {
		cfg = &configfile.Config{}
	}
	if custom := cfg.GetDoltProxiedServerLog(beadsDir); custom != "" {
		return custom, true
	}
	root, _ := resolveProxiedServerRootPath(beadsDir, cfg)
	return filepath.Join(root, proxiedServerLogName), false
}

// ensureProxiedServerConfig resolves the proxied dolt sql-server YAML path
// and guarantees a usable file is on disk, returning the path. Two modes:
//
//   - Default location (no override configured): mkdir the proxieddb root if
//     missing, write a freshly-rendered YAML with a free port baked in if
//     the file is missing, then return. The picked port is sticky across
//     bd invocations to keep the running daemon's listener stable.
//
//   - Custom location (BEADS_PROXIED_SERVER_CONFIG env or
//     metadata.json's dolt_proxied_server_config): the user owns the file.
//     bd never auto-creates it. We validate that it exists, is a regular
//     file, and parses through dolt's own loader — failing fast at config
//     time rather than at daemon-spawn time.
//
// cfg may be nil when init runs before metadata.json is on disk; the env
// var is still honored in that case.
func ensureProxiedServerConfig(beadsDir string, cfg *configfile.Config) (string, error) {
	path, isCustom := resolveProxiedServerConfigPath(beadsDir, cfg)

	if isCustom {
		info, err := os.Stat(path)
		if err != nil {
			return "", fmt.Errorf("ensureProxiedServerConfig: custom config %s: %w", path, err)
		}
		if !info.Mode().IsRegular() {
			return "", fmt.Errorf("ensureProxiedServerConfig: custom config %s: not a regular file", path)
		}
		if _, err := servercfg.YamlConfigFromFile(filesys.LocalFS, path); err != nil {
			return "", fmt.Errorf("ensureProxiedServerConfig: custom config %s: parse: %w", path, err)
		}
		return path, nil
	}

	// Match the YAML's parent directory rather than calling
	// proxiedServerRoot(beadsDir) directly: when --server-root-path is set,
	// resolveProxiedServerConfigPath cascaded `path` under the resolved root,
	// so the mkdir target needs to follow.
	root := filepath.Dir(path)
	if err := os.MkdirAll(root, config.BeadsDirPerm); err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: mkdir %s: %w", root, err)
	}

	switch _, err := os.Stat(path); {
	case err == nil:
		return path, nil
	case !os.IsNotExist(err):
		return "", fmt.Errorf("ensureProxiedServerConfig: stat %s: %w", path, err)
	}

	port, err := proxy.PickFreePort()
	if err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: pick free port: %w", err)
	}

	body, err := renderProxiedServerConfig(port)
	if err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: render YAML: %w", err)
	}
	if err := os.WriteFile(path, body, 0o600); err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: write %s: %w", path, err)
	}
	return path, nil
}

// validateProxiedServerConfig enforces the contract --server-config carries:
// the path must exist, be a regular file, and parse via dolt's own
// servercfg loader. Init invokes this before any side effects so a bad
// config aborts the run with a clear message rather than failing later
// when the daemon tries to spawn against it.
func validateProxiedServerConfig(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		return fmt.Errorf("--server-config %s: %w", path, err)
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("--server-config %s: not a regular file", path)
	}
	if _, err := servercfg.YamlConfigFromFile(filesys.LocalFS, path); err != nil {
		return fmt.Errorf("--server-config %s: parse: %w", path, err)
	}
	return nil
}

// validateProxiedServerRootPath enforces the contract --server-root-path
// carries: the path is allowed to NOT exist (the runtime constructor's
// os.MkdirAll in internal/storage/doltserver/store.go creates it on first
// daemon spawn — same way <beadsDir>/proxieddb is created today). If the
// path DOES exist, it must be a directory; we reject regular files,
// symlinks-to-files, named pipes, etc., to fail loudly here instead of
// inside dolt's filesys layer. Writability is not probed: subsequent
// mkdir / lockfile / pidfile / log open calls will surface permission
// problems crisply if anything is off.
func validateProxiedServerRootPath(path string) error {
	switch info, err := os.Stat(path); {
	case err == nil:
		if !info.IsDir() {
			return fmt.Errorf("--server-root-path %s: not a directory", path)
		}
	case !os.IsNotExist(err):
		return fmt.Errorf("--server-root-path %s: %w", path, err)
	}
	return nil
}

// validateProxiedServerLogPath enforces the contract --server-log-path carries:
// the parent directory must exist (bd never auto-creates arbitrary user
// directories — the user gave us this path and they own its placement),
// and IF the log file itself already exists it must be a regular file
// (reject directories, named pipes, symlinks-to-dirs). The file is allowed
// to NOT exist; the proxy parent's O_CREATE|O_APPEND open at
// internal/storage/db/proxy/endpoint.go will create it on first daemon
// spawn. We don't probe writability — the daemon's open will surface
// permission errors crisply if anything is wrong.
func validateProxiedServerLogPath(path string) error {
	parent := filepath.Dir(path)
	parentInfo, err := os.Stat(parent)
	if err != nil {
		return fmt.Errorf("--server-log-path %s: parent directory: %w", path, err)
	}
	if !parentInfo.IsDir() {
		return fmt.Errorf("--server-log-path %s: parent %s is not a directory", path, parent)
	}
	switch info, err := os.Stat(path); {
	case err == nil:
		if !info.Mode().IsRegular() {
			return fmt.Errorf("--server-log-path %s: not a regular file", path)
		}
	case !os.IsNotExist(err):
		return fmt.Errorf("--server-log-path %s: %w", path, err)
	}
	return nil
}

func renderProxiedServerConfig(port int) ([]byte, error) {
	host := proxiedServerListenerHost
	logLevel := string(servercfg.LogLevel_Info)
	yc := &servercfg.YAMLConfig{
		LogLevelStr: &logLevel,
		ListenerConfig: servercfg.ListenerYAMLConfig{
			HostStr:    &host,
			PortNumber: &port,
		},
	}
	return yaml.Marshal(yc)
}

const proxiedServerListenerHost = "127.0.0.1"

func newProxiedServerStore(ctx context.Context, cfg *dolt.Config) (storage.DoltStorage, error) {
	if cfg == nil {
		return nil, fmt.Errorf("newProxiedServerStore: cfg is nil")
	}
	if cfg.BeadsDir == "" {
		return nil, fmt.Errorf("newProxiedServerStore: cfg.BeadsDir must be set")
	}
	if cfg.Database == "" {
		return nil, fmt.Errorf("newProxiedServerStore: cfg.Database must be set")
	}

	doltBin, err := exec.LookPath("dolt")
	if err != nil {
		return nil, fmt.Errorf("newProxiedServerStore: dolt is not installed (not found in PATH); install from https://docs.dolthub.com/introduction/installation: %w", err)
	}

	// Best-effort: metadata.json carries the configured proxied-server overrides
	// (root path, config, log) if any. At init time the file may not exist yet —
	// pass nil in that case and let the resolvers fall through to env var or
	// default.
	persisted, _ := configfile.Load(cfg.BeadsDir)

	// Resolve the proxied-server root first so config/log resolvers cascade off
	// the right root. Validate when custom so a stale metadata.json entry
	// (path replaced with a regular file, etc.) fails loudly here instead of
	// surfacing as a confusing dolt filesys error.
	rootPath, isCustomRoot := resolveProxiedServerRootPath(cfg.BeadsDir, persisted)
	if isCustomRoot {
		if err := validateProxiedServerRootPath(rootPath); err != nil {
			return nil, err
		}
	}

	configPath, err := ensureProxiedServerConfig(cfg.BeadsDir, persisted)
	if err != nil {
		return nil, err
	}

	// Resolve the daemon's log path from the same configfile load. When
	// custom (env or metadata.json), validate the path so a stale entry
	// (parent dir removed, file replaced with a directory, etc.) fails
	// loudly here instead of crashing the daemon downstream.
	logPath, isCustomLog := resolveProxiedServerLogPath(cfg.BeadsDir, persisted)
	if isCustomLog {
		if err := validateProxiedServerLogPath(logPath); err != nil {
			return nil, err
		}
	}

	name, email := cfg.CommitterName, cfg.CommitterEmail
	if name == "" || email == "" {
		fallbackName, fallbackEmail := proxiedServerCommitter()
		if name == "" {
			name = fallbackName
		}
		if email == "" {
			email = fallbackEmail
		}
	}

	return proxieddolt.NewDoltServerStore(
		ctx,
		rootPath,
		cfg.BeadsDir,
		cfg.Database,
		name, email,
		logPath,
		configPath,
		proxy.BackendLocalServer,
		false, // autoSyncToOriginRemote — wired in a future iteration
		"root",
		"", // rootPassword: proxy is loopback-only, no auth
		doltBin,
	)
}

func proxiedServerCommitter() (string, string) {
	name, email := "beads", "beads@localhost"
	if out, err := exec.Command("git", "config", "user.name").Output(); err == nil {
		if v := strings.TrimSpace(string(out)); v != "" {
			name = v
		}
	}
	if out, err := exec.Command("git", "config", "user.email").Output(); err == nil {
		if v := strings.TrimSpace(string(out)); v != "" {
			email = v
		}
	}
	return name, email
}
